catalog:
    path: /
    methods: GET
    controller: App\Controller\ProductController::overview

viewProduct:
    path: /product/{productId}
    methods: GET
    controller: App\Controller\ProductController::getProduct
    requirements:
        productId: '\d+'

createProductView:
    path: /product/create   
    methods: 'GET'
    controller: App\Controller\ProductController::createProductView

createProduct:
    path: /product/create
    methods: 'POST'
    controller: App\Controller\ProductController::createProduct

updateProductView:
    path: /product/update/{productId}   
    methods: 'GET'
    controller: App\Controller\ProductController::updateProductView
    requirements:
        productId: '\d+'

updateProduct:
    path: /product/update/{productId}
    methods: 'POST'
    controller: App\Controller\ProductController::updateProduct
    requirements:
        productId: '\d+'

deleteProduct:
    path: /product/delete/{productId}
    methods: ['GET', 'POST']   #TODO: изменить потом на Only POST, request by js fetch, no window.location
    controller: App\Controller\ProductController::deleteProduct
    requirements:
        productId: '\d+'

loginView:
    path: /login
    methods: 'GET'
    controller: App\Controller\LoginController::index

login:
    path: /login
    methods: 'POST'

registerView:
    path: /register
    methods: 'GET'
    controller: App\Controller\RegisterController::index

register:
    path: /register
    methods: 'POST'
    controller: App\Controller\RegisterController::register

profile:
    path: /profile
    methods: 'GET'
    controller: App\Controller\UserController::profile